stages:
  - build
  - deploy

variables:
  SERVICE: bf-bot
  IMAGE: registry.gitlab.com/fedya-mercuriev/${SERVICE}:${CI_BUILD_REF_NAME}

build:
  stage: build
  image: docker
  services:
    - docker:dind
  script:
    - docker build -t ${IMAGE} .
    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} registry.gitlab.com
    - docker push ${IMAGE}
  only:
    - /^feature.*$/
    - master
  tags:
    - docker

deploy:
  stage: deploy
  variables:
    TOKEN: ${TOKEN}
  script:
    - docker rm $(docker ps -aq) || true
    - docker rmi $(docker images -aq) || true
    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} registry.gitlab.com
    - docker pull $IMAGE
    - echo ${TOKEN}
    - docker run -d
                 -p 443:443
                 -p 8080:8080
                 --env TOKEN
                 --name $SERVICE $IMAGE
  only:
    - /^feature.*$/
    - master
  tags:
    - beta-deploy