stages:
  - build
  - deploy

variables:
  SERVICE: bf-bot
  IMAGE: registry.gitlab.com/fedya-mercuriev/${SERVICE}:${CI_BUILD_REF_NAME}

build:
  stage: build
  image: docker
  services:
    - docker:dind
  script:
    - docker build -t ${IMAGE} .
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} registry.gitlab.com
    - docker push ${IMAGE}
  only:
    - /^feature.*$/
    - master
#  when: manual
  tags:
    - docker

deploy:
  stage: deploy
  script:
    - docker rm -f $(docker ps -aq) || true
    - docker rmi -f $(docker images -aq) || true
    - TOKEN=${TOKEN}
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} registry.gitlab.com
    - docker pull $IMAGE
    - docker run -d
                 -p 443:443
                 -p 8080:8080
                 --env TOKEN="${TOKEN}"
                 --name $SERVICE $IMAGE
  only:
    - /^feature.*$/
    - master
  tags:
    - beta-deploy