stages:
  - build
  - deploy

variables:
  SERVICE: bf-bot
  IMAGE_NAME: registry.gitlab.com/fedya-mercuriev/${SERVICE}:${CI_BUILD_REF_NAME}

build:
  stage: build
  image: docker
  services:
    - docker:dind
  script:
    - docker build -t ${IMAGE_NAME} .
    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} registry.gitlab.com
    - docker push ${IMAGE_NAME}
  only:
    - /^feature.*$/
    - master
  tags:
    - docker

deploy:
  stage: deploy
  image: docker
  services:
    - docker:dind
  script:
   - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} registry.gitlab.com
   - docker pull ${IMAGE}
   - docker run -d \
                -p 443:443 \
                -p 8080:8080 \
                -e TOKEN=${TOKEN} \
                -t ${SERVICE} ${IMAGE_NAME}
  only:
   - /^feature.*$/
   - master
  tags:
   - beta-deploy